ERROR - 2022-12-28 19:21:38 --> mysqli_sql_exception: Cannot delete or update a parent row: a foreign key constraint fails (`tienda`.`venta`, CONSTRAINT `venta_ibfk_1` FOREIGN KEY (`factura_Id`, `factura_cliente_Id`) REFERENCES `factura` (`Id`, `cliente_Id`)) in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `factura...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `factura...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `factura...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `factura...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(51): CodeIgniter\Model->update('4', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->editar('4')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-28 19:22:01 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tienda`.`venta`, CONSTRAINT `venta_ibfk_1` FOREIGN KEY (`factura_Id`, `factura_cliente_Id`) REFERENCES `factura` (`Id`, `cliente_Id`)) in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(49): CodeIgniter\Model->update('24', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('24')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-28 19:22:02 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tienda`.`venta`, CONSTRAINT `venta_ibfk_1` FOREIGN KEY (`factura_Id`, `factura_cliente_Id`) REFERENCES `factura` (`Id`, `cliente_Id`)) in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(49): CodeIgniter\Model->update('24', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('24')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-28 19:22:03 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tienda`.`venta`, CONSTRAINT `venta_ibfk_1` FOREIGN KEY (`factura_Id`, `factura_cliente_Id`) REFERENCES `factura` (`Id`, `cliente_Id`)) in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(49): CodeIgniter\Model->update('24', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('24')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-28 19:22:03 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tienda`.`venta`, CONSTRAINT `venta_ibfk_1` FOREIGN KEY (`factura_Id`, `factura_cliente_Id`) REFERENCES `factura` (`Id`, `cliente_Id`)) in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(49): CodeIgniter\Model->update('24', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('24')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-28 19:22:04 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tienda`.`venta`, CONSTRAINT `venta_ibfk_1` FOREIGN KEY (`factura_Id`, `factura_cliente_Id`) REFERENCES `factura` (`Id`, `cliente_Id`)) in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(49): CodeIgniter\Model->update('24', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('24')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-28 19:22:04 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tienda`.`venta`, CONSTRAINT `venta_ibfk_1` FOREIGN KEY (`factura_Id`, `factura_cliente_Id`) REFERENCES `factura` (`Id`, `cliente_Id`)) in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(49): CodeIgniter\Model->update('24', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('24')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-28 19:23:24 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('4')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('4')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-28 19:23:24 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('4')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('4')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-28 19:35:55 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-28 19:35:55 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-28 19:37:15 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(32): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-28 19:37:15 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 33.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-28 19:38:05 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(32): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-28 19:38:05 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 33.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-28 19:56:07 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tienda`.`venta`, CONSTRAINT `venta_ibfk_1` FOREIGN KEY (`factura_Id`) REFERENCES `factura` (`Id`)) in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(49): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-28 19:58:02 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tienda`.`venta`, CONSTRAINT `venta_ibfk_1` FOREIGN KEY (`factura_Id`) REFERENCES `factura` (`Id`)) in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `venta` ...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `venta` ...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `venta` ...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `venta` ...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(49): CodeIgniter\Model->update('1', Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->editar('1')
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
